
# Site settings

url: "https://jeevananm06.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"

baseurl: /personal-jekyll-theme

google-tracking-id: "UA-35880426-4"

# Forces https everywhere in your website, except when you serve it locally

force-https: True

#############
# HTML Head #
#############

author: "Jeevanantham Govindaraju"
lang: "en"
title: "{ Jeeva }"
favicon: "/img/favicon.ico"
description: "Blog and website of Jeeva, blogging mainly for tech. Opinions expressed are mine."
keywords: "smith, jones, personal, jekyll, theme"

################
# Intro layout #
################

black-favicon: "/img/black-lab-glass.ico"
background-img: "/img/main_back1.jpg"
me-img: "/img/IMG_Me.jpg"

##############################
# Dynamic Text on the header #
##############################

dynamic-typing: True
shuffle: True	# Shuffle the lines.
loop: True
loop-count:	False # Set False for infinite loop, or set any number for finite loop.
type-speed:	10		# Default 10
start-delay: 200	# Default 200
delete-delay: 5000	# Default 5000
lines:			# You can add HTML Tags in the Text
  - text: "The lower you fall, the higher you'll fly."
 # - text: "Where’s your will to be weird?"

########
# Blog #
########

post-preview-words: 96

paginate: 5

fb-share: True
twitter-share: True
reddit-share: True
disqus-shortname: "Jeevanantham"

###############
# Life Events #
###############

events:
  - image: "/img/career/cognizant.jpg"
    date: "January 2011 - today"
    description: "Started working in Cognizant and continuing"
  - image: "/img/career/KCT Logo.jpg"
    date: "January 2006 - May 2010"
    description: "Completed my Bachelor Degree "

# First image of the Career timeline
career-img: "/img/career/frontpage_reader.jpg"

##################
# Contact layout #
##################

email: "jeevananm06@gmail.com"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/jeeva1988"
  - title: "twitter"
    url: "https://twitter.com/jeeva1988"
  - title: "linkedin"
    url: "https://in.linkedin.com/in/jeevanantham-govindaraju-4072b721"
  - title: "github"
    url: "https://github.com/jeevananm06"
  - title: "stack-overflow"
    url: "http://stackoverflow.com/users/3066872/jeeva?tab=profile"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# Tread carefully if you want to change the variables below this point!

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  Blog: 'blog'
  Career: 'career'
  Contact: 'contact'

# Pagination path
paginate_path: "blog/page:num"

# Enable minification SASS
sass:
  style: compressed

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]

gems: [jekyll-paginate]
